language: shell
os: linux

notifications:
  email:
    on_success: never
    on_failure: always

services:
  - docker
env:
  - OLS_VERSION=1.6.21 PHP_VERSION=80 FOLDER=ub18-template TAG=latest、
  - OLS_VERSION=1.6.21 PHP_VERSION=80 FOLDER=ub18-template
  - OLS_VERSION=1.6.21 PHP_VERSION=74 FOLDER=ub18-template
  - OLS_VERSION=1.6.21 PHP_VERSION=73 FOLDER=ub18-template
  - OLS_VERSION=1.6.21 PHP_VERSION=72 FOLDER=ub18-template
  - OLS_VERSION=1.6.21 PHP_VERSION=71 FOLDER=ub18-template
  - OLS_VERSION=1.6.21 PHP_VERSION=70 FOLDER=ub18-template
  - OLS_VERSION=1.6.21 PHP_VERSION=56 FOLDER=ub16-template
  - OLS_VERSION=1.6.21 PHP_VERSION=55 FOLDER=ub16-template
  - OLS_VERSION=1.6.21 PHP_VERSION=54 FOLDER=ub16-template
  - OLS_VERSION=1.6.21 PHP_VERSION=53 FOLDER=ub14-template
  - OLS_VERSION=1.7.10 PHP_VERSION=80 FOLDER=ub18-template
  - OLS_VERSION=1.7.10 PHP_VERSION=74 FOLDER=ub18-template
  - OLS_VERSION=1.7.10 PHP_VERSION=73 FOLDER=ub18-template
  - OLS_VERSION=1.7.10 PHP_VERSION=72 FOLDER=ub18-template
  - OLS_VERSION=1.7.10 PHP_VERSION=71 FOLDER=ub18-template
  - OLS_VERSION=1.7.10 PHP_VERSION=70 FOLDER=ub18-template
  - OLS_VERSION=1.7.10 PHP_VERSION=56 FOLDER=ub16-template
  - OLS_VERSION=1.7.10 PHP_VERSION=55 FOLDER=ub16-template
  - OLS_VERSION=1.7.10 PHP_VERSION=54 FOLDER=ub16-template
  - OLS_VERSION=1.7.10 PHP_VERSION=53 FOLDER=ub14-template

script:
  - |
    if [ $TRAVIS_BRANCH == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        cd $FOLDER && bash build.sh --ols $OLS_VERSION --php $PHP_VERSION --tag "$TAG" --push
    else
        cd $FOLDER && bash build.sh --ols $OLS_VERSION --php $PHP_VERSION
    fi    